categories:
  - id: smartphones
    queries:
      - "smartphones under 20000"
      - "best smartphones 2025"
    top_m: 50
    weights:
      spec: 0.4
      price: 0.3
      rating: 0.2
      reviews: 0.1
    notify_if:
      enters_top_k: 5
      price_drop_pct: 8
      vfm_score_delta: 0.08

  - id: truewireless
    queries:
      - "true wireless earphones"
    top_m: 40
    weights:
      spec: 0.25
      price: 0.45
      rating: 0.2
      reviews: 0.1
    notify_if:
      price_drop_pct: 12
